(function() {
  const screens = [
    { id: 1, short: 'Job Dashboard', file: '01-job-dashboard.html' },
    { id: 2, short: 'Registration CTA', file: '02-registration-cta.html' },
    { id: 3, short: 'Onboarding', file: '03-onboarding-personal.html' },
  ];
  const currentFile = window.location.pathname.split('/').pop() || '';
  const currentIdx = screens.findIndex(s => currentFile.includes(s.file.replace('.html', '')));
  if (currentIdx === -1) return;
  if (window.location.hash.includes('figmacapture')) { const s=document.createElement('script');s.src='https://mcp.figma.com/mcp/html-to-design/capture.js';document.head.appendChild(s);return; }
  const btns = screens.map((s, i) => { const active=i===currentIdx; const cls=active?'px-3 py-1.5 text-xs rounded-md font-medium whitespace-nowrap bg-[#007F7E] text-white shadow-[0_0_0_2px_rgba(67,192,190,0.5)]':'px-3 py-1.5 text-xs rounded-md font-medium whitespace-nowrap bg-gray-700 hover:bg-gray-600 text-gray-300 cursor-pointer'; const nc=active?'text-white/60':'text-gray-500'; return active?`<span class="${cls}"><span class="${nc} mr-1">${String(s.id).padStart(2,'0')}</span>${s.short}</span>`:`<a href="${s.file}" class="${cls}" style="text-decoration:none;"><span class="${nc} mr-1">${String(s.id).padStart(2,'0')}</span>${s.short}</a>`; }).join(' ');
  const toolbar=document.createElement('div');toolbar.id='mockup-toolbar-panel';toolbar.className='fixed top-0 left-0 right-0 z-[9999]';
  toolbar.innerHTML=`<div class="bg-gray-800/95 backdrop-blur border-b border-gray-700 px-4 py-3"><div class="max-w-7xl mx-auto flex items-center justify-between"><div class="flex items-center gap-4"><div class="flex items-center gap-2"><div class="w-6 h-6 bg-amber-600 rounded flex items-center justify-center text-xs font-bold text-white">DD</div><h1 class="text-base font-semibold text-white">CPV — Dashboard Dan</h1></div><span class="text-gray-600">|</span><span class="text-gray-400 text-sm">${String(screens[currentIdx].id).padStart(2,'0')} — ${screens[currentIdx].short}</span></div><div class="flex items-center gap-2"><button id="figma-copy-btn" class="flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-md font-medium bg-gray-700/80 text-gray-300 cursor-pointer border border-gray-600 hover:bg-gray-600 hover:text-white">Copy Page <kbd class="ml-0.5 bg-gray-600 px-1 py-0.5 rounded text-[10px] text-gray-400 font-mono">F</kbd></button><span class="text-xs text-gray-500 ml-1">${currentIdx+1} / ${screens.length}</span></div></div></div><div class="bg-gray-800/80 backdrop-blur px-4 py-2 border-b border-gray-700/50"><div class="max-w-7xl mx-auto flex items-center gap-1.5 overflow-x-auto">${btns}</div></div>`;
  document.body.style.paddingTop='88px';document.body.insertBefore(toolbar,document.body.firstChild);
  let capturing=false;
  document.getElementById('figma-copy-btn').addEventListener('click',function(){if(capturing)return;capturing=true;toolbar.style.display='none';document.body.style.paddingTop='0';const s=document.createElement('script');s.src='https://mcp.figma.com/mcp/html-to-design/capture.js';s.onload=function(){setTimeout(function(){toolbar.style.display='';document.body.style.paddingTop='88px';capturing=false;},4000);};document.head.appendChild(s);});
  let visible=true;
  document.addEventListener('keydown',(e)=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='Escape'){visible=!visible;toolbar.style.transform=visible?'translateY(0)':'translateY(-100%)';document.body.style.paddingTop=visible?'88px':'0';return;}if(e.key==='f'||e.key==='F'){document.getElementById('figma-copy-btn').click();return;}if(e.key==='ArrowRight'&&currentIdx<screens.length-1){window.location.href=screens[currentIdx+1].file;return;}if(e.key==='ArrowLeft'&&currentIdx>0){window.location.href=screens[currentIdx-1].file;return;}const num=parseInt(e.key);if(num>=1&&num<=screens.length)window.location.href=screens[num-1].file;});
})();
